baseurl: "/ctp" # "/communitytechnology" 
name: "Community Technology Initiative"
description: ""
title: Community Technology Initiative

title0: Re(Building) Technology

exclude: [CNAME, README.md, .gitignore, list_assests.pl]
permalink: /:categories/:title/ 

encoding: utf-8
markdown: kramdown

imageurl: files