baseurl: ""    #"/ct-platform" 
name: ""
description: ""
title: Community Technology Field Guide

header: (Re)Building Technology

exclude: [CNAME, README.md, .gitignore, list_assests.pl]
permalink: /:categories/:title/ 

encoding: utf-8 
markdown: kramdown

imageurl: files

prose:
 siteurl: "http://communitytechnology.github.io"
 ignore: 
  - /_layouts
  - /_includes 
  - /index.md
  - list-assets.md
  - list-assets.pl
  - .gitignore
  - /css
  - /fonts
  - /assets
  - /icons
  - _config.yml
