baseurl: ""    #"/ct-platform" 
name: ""
description: ""
title: Community Technology Fieldbook 

title0: Re(Building) Technology

exclude: [CNAME, README.md, .gitignore, list_assests.pl]
permalink: /:categories/:title/ 

encoding: utf-8 
markdown: kramdown

imageurl: files

prose:
 siteurl: "http://communitytechnology.github.io"
 ignore: 
  - /_layouts
  - /_includes 
  - index.md
  metadata:
   docs:
    - name: "layout"
      field: 
       element: select
       options:
        - name: 'Blog'
          value: 'blog'
        - name: 'Collection'
          value: 'collection'