baseurl: "/ctp" # "/communitytechnology" 
name: "Community Technology"
description: "communitytechnology"
title: Re(Building) Technology

exclude: [CNAME, README.md, .gitignore, list_assests.pl]
permalink: /:categories/:title/ 

encoding: utf-8
markdown: kramdown

imageurl: files